repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.55.5
    hooks:
    -   id: swiftformat
-   repo: https://github.com/realm/SwiftLint
    rev: 0.58.2
    hooks:
    -   id: swiftlint
