name: Update Build Number
run-name: ${{ github.actor }} is updating the build version ðŸ› ï¸
on:
  pull_request:
    types: [ labeled ]
jobs:
  Update-Build-Number:
    if: github.event.label.name == 'Ready for Testing'
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./PlaybookSwift
    env:
      # Set an environment variable for the branch name
      BRANCH_NAME: ${{ github.head_ref }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Set Git Config
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Get Build Number
        run: |
          echo $(git config user.name)
          echo $(git config user.email)
          git clone --depth 5 git@github.com:powerhome/nitro-buildnumber.git .
          echo $(ls nitro-buildnumber)
          "666" >> ./buildNumber.txt
          echo $(cat ./buildNumber.txt)
      # - name: Leave PR comment
      #   env:
      #     PR_NUMBER: ${{ github.event.pull_request.number }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     RUBY_GEM_VERSION: ${{ env.new_ruby_alpha_version }}
      #     RUBY_GEM_LINK: https://rubygems.org/gems/playbook_ui/versions/${{env.new_ruby_alpha_version}}
      #     NPM_VERSION: ${{ env.new_npm_alpha_version }}
      #     NPM_LINK: https://www.npmjs.com/package/playbook-ui/v/${{env.new_npm_alpha_version}}
      #   run: |
      #     curl -H "Authorization: token ${GITHUB_TOKEN}" \
      #         -X POST \
      #         -d '{"body": "ðŸŽ‰ Congratulations on creating an Alpha Version! \n\n Your Alpha for Ruby Gems is [${{env.RUBY_GEM_VERSION}}](${{env.RUBY_GEM_LINK}}) \n\n Your Alpha for NPM is [${{env.NPM_VERSION}}](${{env.NPM_LINK}}) "}' \
      #           "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"
